### ISSUE TITLE
checkpoints for the models

### ISSUE THREAD

**Issue by scy639** [L-Scofano/STAG#2]
Wonderful work!
I was wondering if it would be possible for you to release the model checkpoints. That would greatly aid in further research and development efforts.

**Comment by L-Scofano** [comment]
Thank you for your interest in our work! 
I apologize for the delayed response as I'm currently out of office. We'll do our best to release the model checkpoints as soon as possible. 
In the meantime, if you need any clarification on the training setup, please don't hesitate to ask. We're here to help!
